name: Java CI with Gradle

on:
  push:
    branches: [ "develop", "feature/" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Build with Gradle
      run: gradle build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/libs/**

    - name: Run Unit Test
      run: gradle test

    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: build/reports/tests/**

    - name: Generate code coverage report
      run: gradle jacocoTestReport

    - name: Upload code coverage report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: build/reports/jacoco/test/html/**

    - name: Run Deployment
      run: java -jar build/libs/hello-world-java-V1.jar
